apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 10-oot-ice
spec:
  config:
    ignition:
     version: 3.2.0
    storage:
      files:
        - contents:
            source: 'data:text/plain;charset=us-ascii;base64,IyEvYmluL2Jhc2gKc2V0IC1ldQoKQUNUSU9OPSQxOyBzaGlmdApJTUFHRT0kMTsgc2hpZnQKS0VSTkVMPWB1bmFtZSAtcmAKCnBvZG1hbiBwdWxsIC0tdGxzLXZlcmlmeT1mYWxzZSAtLWF1dGhmaWxlIC92YXIvbGliL2t1YmVsZXQvY29uZmlnLmpzb24gJHtJTUFHRX06JHtLRVJORUx9IDI+JjEKCmxvYWRfa21vZHMoKSB7CgogICAgcG9kbWFuIHJ1biAtaSAtLXByaXZpbGVnZWQgXAogICAgICAtdiAvbGliL21vZHVsZXMvJHtLRVJORUx9L2tlcm5lbC9kcml2ZXJzLzovbGliL21vZHVsZXMvJHtLRVJORUx9L2tlcm5lbC9kcml2ZXJzLyBcCiAgICAgIC12IC92YXIvbGliLzovdmFyL2xpYi8gXAogICAgICAke0lNQUdFfToke0tFUk5FTH0gbG9hZC5zaAp9CnVubG9hZF9rbW9kcygpIHsKICAgIHBvZG1hbiBydW4gLWkgLS1wcml2aWxlZ2VkIFwKICAgICAgLXYgL2xpYi9tb2R1bGVzLyR7S0VSTkVMfS9rZXJuZWwvZHJpdmVycy86L2xpYi9tb2R1bGVzLyR7S0VSTkVMfS9rZXJuZWwvZHJpdmVycy8gXAogICAgICAtdiAvdmFyL2xpYi86L3Zhci9saWIvIFwKICAgICAgJHtJTUFHRX06JHtLRVJORUx9IHVubG9hZC5zaAp9CgpjYXNlICIke0FDVElPTn0iIGluCiAgICBsb2FkKQogICAgICAgIGxvYWRfa21vZHMKICAgIDs7CiAgICB1bmxvYWQpCiAgICAgICAgdW5sb2FkX2ttb2RzCiAgICA7OwogICAgKikKICAgICAgICBlY2hvICJVbmtub3duIGNvbW1hbmQuIEV4aXRpbmcuIgogICAgICAgIGVjaG8gIlVzYWdlOiIKICAgICAgICBlY2hvICIiCiAgICAgICAgZWNobyAibG9hZCAgICAgICAgTG9hZCBrZXJuZWwgbW9kdWxlKHMpIgogICAgICAgIGVjaG8gInVubG9hZCAgICAgIFVubG9hZCBrZXJuZWwgbW9kdWxlKHMpIgogICAgICAgIGV4aXQgMQplc2FjCg=='
          filesystem: root
          mode: 493
          path: /usr/local/bin/oot-ice
    systemd:
      units:
      - contents: |
          [Unit]
          Description=out-of-tree driver loader
          # Start after the network is up
          Wants=network-online.target
          After=network-online.target
          # Also after docker.service (no effect on systems without docker)
          After=docker.service
          # Before kubelet.service (no effect on systems without kubernetes)
          Before=kubelet.service

          [Service]
          Type=oneshot
          RemainAfterExit=true
          # Use bash to workaround https://github.com/coreos/rpm-ostree/issues/1936
          ExecStart=/usr/bin/bash -c "/usr/local/bin/oot-ice load  cnfde2.ptp.lab.eng.bos.redhat.com:5000/intel/oot-ice"
          ExecStop=/usr/bin/bash -c "/usr/local/bin/oot-ice unload cnfde2.ptp.lab.eng.bos.redhat.com:5000/intel/oot-ice"
          StandardOutput=journal+console

          [Install]
          WantedBy=default.target
        enabled: true
        name: "oot-ice.service"
  kernelArguments:
    - firmware_class.path=/var/lib/firmware
