apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 99-dell-oot-ice-ext-image
spec:
  osImageURL: quay.io/dosman/coreos-dell-oot-ice:5.14.0-427.13.1.el9_4.x86_64
