apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 99-dosman-external-image 
spec:
  osImageURL: quay.io/dosman/coreos-intel-oot:5.14.0-284.32.1.el9_2.x86_64
