apiVersion: v1
kind: Pod
metadata:
  name: du-testpmd
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
          {
            "mac": "96:77:C0:21:7D:87",
            "name": "sriov-nw-du-mh"
          },
          {
            "mac": "F6:16:6A:00:70:19",
            "name": "sriov-nw-du-fh"
          }
        ]'
    cpu-load-balancing.crio.io: "disable"
    cpu-quota.crio.io: "disable"
    irq-load-balancing.crio.io: "disable"
  namespace: openshift-sriov-network-operator
spec:
  runtimeClassName: performance-openshift-node-performance-profile
  restartPolicy: Never
  containers:
  - name: testpmd
    image: quay.io/dosman/dpdk-testpmd:small
#   command: ["sleep", "infinity"]
#   args: []
    imagePullPolicy: Always #IfNotPresent #
    env:
    - name: FORWARD_MODE
      value: "mac"
    - name: SRIOV_ID_A
      value: "DU_MH"
    - name: SRIOV_ID_B
      value: "DU_FH"
    securityContext:
      runAsUser: 0
      capabilities:
        add: ["IPC_LOCK","SYS_ADMIN","SYS_NICE", "NET_RAW", "SYS_RESOURCE"]
    resources:
      limits:
        cpu: 4
        memory: "1Gi"
        hugepages-1Gi: "4Gi"
      requests:
        cpu: 4
        memory: "1Gi"
        hugepages-1Gi: "4Gi"
    volumeMounts:
    - mountPath: /mnt/huge
      name: hugepage
    - mountPath: /var/run/dpdk
      name: dpdk
  volumes:
  - name: hugepage
    emptyDir:
      medium: HugePages
  - name: dpdk
    emptyDir: {}
